//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGS.Models
{
    using Microsoft.AspNetCore.Identity;
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        public int Id { get; set; }
        public string ExceptionalPortfolioHeading { get; set; }
        public string Disclaimer { get; set; }
        public string PortfolioBackgroundImage { get; set; }
        public string NewsHeading { get; set; }
        public string NewsBackGroundImage { get; set; }
        public string InvestorLogin { get; set; }
        public string vimeoVideoUrl { get; set; }
        public string LinkedInUrl { get; set; }
        public string TwitterUrl { get; set; }
        public string FBUrl { get; set; }
        public string Email { get; set; }
        public string OverviewPdf { get; set; }
        public Nullable<System.DateTime> WebsiteUpdateDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }

        public virtual IdentityUser? CreatedByUser { get; set; }
        public virtual IdentityUser? ModifiedByUser { get; set; }
    }
}
